services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak-idp
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
    ports:
      - "8080:8080"
    command: start-dev
    depends_on:
      - postgres
    networks:
      - idp-network

  postgres:
    image: postgres:13
    container_name: postgres-idp
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - idp-network

volumes:
  postgres_data:

networks:
  idp-network:
    driver: bridge
